#!/bin/sh
# updated 8th feb 2020
curl 'https://www.expressvpn.com/custom_installer?cluster_id=126&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Albania.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=139&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Algeria.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=184&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Andorra.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=88&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Argentina.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=185&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Armenia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=208&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Australia-Brisbane.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=156&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Australia-Melbourne.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=209&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Australia-Perth.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=81&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Australia-Sydney.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=162&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Australia-Sydney-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=21&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Austria.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=135&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Azerbaijan.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=115&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Bahamas.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=192&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Bangladesh.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=186&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Belarus.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=85&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Belgium.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=193&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Bhutan.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=147&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Bosnia_and_Herzegovina.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=163&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Brazil-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=194&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Brunei.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=110&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Bulgaria.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=175&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Cambodia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=45&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Canada-Montreal.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=170&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Canada-Montreal-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=79&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Canada-Toronto.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=169&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Canada-Toronto-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=181&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Canada-Vancouver.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=131&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Colombia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=100&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Costa_Rica.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=118&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Croatia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=124&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Cyprus.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=56&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Czech_Republic.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=78&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Denmark.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=144&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Ecuador.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=84&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Egypt.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=130&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Estonia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=34&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Finland.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=104&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/France-Paris-1.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=8&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/France-Paris-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=103&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/France-Strasbourg.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=136&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Georgia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=7&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Germany-Frankfurt-1.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=158&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Germany-Frankfurt-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=92&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Germany-Frankfurt-3.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=210&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Germany-Nuremberg.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=102&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Greece.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=141&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Guatemala.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=114&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Hong_Kong-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=200&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Hong_Kong-4.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=99&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Hungary.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=106&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Iceland.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=171&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/India-Chennai.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=83&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/India-Mumbai-1.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=112&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Indonesia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=33&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Ireland.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=129&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Isle_of_Man.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=105&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Israel.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=182&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Italy-Cosenza.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=157&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Italy-Milan.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=148&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Japan-Tokyo-1.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=80&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Japan-Tokyo-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=57&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Japan-Tokyo-3.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=188&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Jersey.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=133&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Kazakhstan.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=176&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Kenya.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=123&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Kyrgyzstan.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=195&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Laos.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=122&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Latvia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=119&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Liechtenstein.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=36&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Lithuania.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=12&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Luxembourg.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=174&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Macau.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=111&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Malaysia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=134&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Malta.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=132&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Mexico.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=120&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Moldova.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=187&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Monaco.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=137&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Mongolia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=189&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Montenegro.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=196&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Myanmar.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=197&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Nepal.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=4&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Netherlands-Amsterdam.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=173&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Netherlands-Amsterdam-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=16&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Netherlands-Rotterdam.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=212&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Netherlands-The_Hague.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=113&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/New_Zealand.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=146&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/North_Macedonia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=96&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Norway.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=198&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Pakistan.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=20&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Panama.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=142&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Peru.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=164&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Philippines.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=32&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Poland.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=31&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Portugal.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=86&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Romania.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=145&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Serbia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=107&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Singapore-CBD.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=154&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Singapore-Jurong.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=37&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Singapore-Marina_Bay.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=127&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Slovakia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=121&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Slovenia.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=109&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/South_Africa.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=58&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/South_Korea-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=211&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Spain-Barcelona.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=22&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Spain-Madrid.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=199&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Sri_Lanka.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=23&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Sweden.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=11&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Switzerland.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=201&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Switzerland-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=108&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Taiwan-3.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=101&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Thailand.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=89&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Turkey.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=53&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/UK-Docklands.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=178&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/UK-East_London.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=150&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/UK-Kent.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=5&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/UK-London.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=87&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Ukraine.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=140&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Uruguay.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=19&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Atlanta.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=9&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Chicago.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=18&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Dallas.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=165&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Dallas-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=172&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Denver.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=6&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Los_Angeles.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=149&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Los_Angeles-1.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=70&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Los_Angeles-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=74&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Los_Angeles-3.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=68&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Los_Angeles-4.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=71&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Los_Angeles-5.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=54&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Miami.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=202&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Miami-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=26&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-New_Jersey-1.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=155&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-New_Jersey-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=168&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-New_Jersey-3.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=75&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-New_York.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=191&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-New_York-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=204&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Salt_Lake_City.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=1&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-San_Francisco.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=97&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-San_Jose.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=2&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Seattle.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=166&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Tampa-1.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=25&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Washington_DC.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=180&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/USA-Washington_DC-2.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=128&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Uzbekistan.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=143&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Venezuela.ovpn
curl 'https://www.expressvpn.com/custom_installer?cluster_id=117&amp;code=url_key&amp;os=linux&amp;source=web' -o /tmp/Vietnam.ovpn

